### ISSUE TITLE
Error handling messages - incorrect answer to the secret question

### ISSUE THREAD

**Issue by OphelieC** [B-Souty/OktaLoginWrapper#10]
**Description**
When trying to authenticate, if the wrong answer is given when prompted to answer the secrete question, an error is thrown. 

**Steps**
1. Open your instance
2. Trigger the secrete question
`my_session.okta_auth('name', 'password', factor_type='question' )`
3. Answer with an incorrect answer

**Expected behavior**
An error message is displayed.
Or see notes below.

**Current behavior**
The following error is sent:
>Traceback (most recent call last):
> File "<input>", line 1, in <module>
> File "<input>", line 75, in okta_auth
> File "<input>", line 114, in _okta_verify
>AttributeError: 'NoneType' object has no attribute 'get'

**Notes**
If the `factor_type = 'token'` and the wrong token is given, then the user is prompted to type the OTP again. same behavior could be expected.

**Comment by stosh-malec** [comment]
Hello! I currently have a pull request in that will resolve this issue! The OTP and question issue will be addressed in a future contribution!
