### ISSUE TITLE
Need help from someone with Okta account and push notification as MFA for test

### ISSUE THREAD

**Issue by B-Souty** [B-Souty/OktaLoginWrapper#4]
Hi,

I have been using this script succesfuly myself but I never had the chance to test it on a different okta instance than mine.

I need someone with an Okta account to test this script so I know I can finally relax knowing that it will work for everyone.

Note: Make sure you have **push notification enabled has second factor**, otherwise the script will crash. I will add more factors in the nezr future.

**Comment by ktugan** [comment]
Hi B-Scouty, it works for me with the exception that I had to fork it for my european account.

That is `okta-emea.com` instead of `okta.com`.

**Comment by B-Souty** [comment]
@ktugan Thanks for your feedback, good to know finally it's working for others as well. Indeed I didn't know there was an endpoint for emea. Not sure if this is because of GDPR or if apac also has its own endpoint. In any case, I'll check if I can update so that the full instance has to be be specified when connecting.

**Comment by stosh-malec** [comment]
Also works for me in the US.
